package org.flexpay.ab.persistence.temp;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.*;
import java.util.Date;

/**
 * ApartmentAttribute generated by hbm2java
 */
@Entity
@Table (name = "apartment_attribute"
		, catalog = "flexpay_db"
)
public class ApartmentAttribute implements java.io.Serializable {


	private int id;
	private Apartment apartment;
	private ApartmentAttributeType apartmentAttributeType;
	private Date begin;
	private Date end;
	private String value;

	public ApartmentAttribute() {
	}


	public ApartmentAttribute(int id, Date begin, Date end, String value) {
		this.id = id;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	public ApartmentAttribute(int id, Apartment apartment, ApartmentAttributeType apartmentAttributeType, Date begin, Date end, String value) {
		this.id = id;
		this.apartment = apartment;
		this.apartmentAttributeType = apartmentAttributeType;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	@Id

	@Column (name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Apartment_ID")
	public Apartment getApartment() {
		return this.apartment;
	}

	public void setApartment(Apartment apartment) {
		this.apartment = apartment;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Apartment_Attribute_type_ID")
	public ApartmentAttributeType getApartmentAttributeType() {
		return this.apartmentAttributeType;
	}

	public void setApartmentAttributeType(ApartmentAttributeType apartmentAttributeType) {
		this.apartmentAttributeType = apartmentAttributeType;
	}

	@Column (name = "begin", nullable = false, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", nullable = false, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column (name = "value", nullable = false, length = 2000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}


