package org.flexpay.ab.persistence.temp;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApartmentAttributeType generated by hbm2java
 */
@Entity
@Table(name="apartment_attribute_type"
    ,catalog="flexpay_db"
)
public class ApartmentAttributeType  implements java.io.Serializable {


     private int id;
     private String attributeTypeCode;
     private Set<ApartmentAttributeTypeName> apartmentAttributeTypeNames = new HashSet<ApartmentAttributeTypeName>(0);
     private Set<ApartmentAttribute> apartmentAttributes = new HashSet<ApartmentAttribute>(0);

    public ApartmentAttributeType() {
    }

	
    public ApartmentAttributeType(int id, String attributeTypeCode) {
        this.id = id;
        this.attributeTypeCode = attributeTypeCode;
    }
    public ApartmentAttributeType(int id, String attributeTypeCode, Set<ApartmentAttributeTypeName> apartmentAttributeTypeNames, Set<ApartmentAttribute> apartmentAttributes) {
       this.id = id;
       this.attributeTypeCode = attributeTypeCode;
       this.apartmentAttributeTypeNames = apartmentAttributeTypeNames;
       this.apartmentAttributes = apartmentAttributes;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="attribute_type_code", nullable=false)
    public String getAttributeTypeCode() {
        return this.attributeTypeCode;
    }
    
    public void setAttributeTypeCode(String attributeTypeCode) {
        this.attributeTypeCode = attributeTypeCode;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="apartmentAttributeType")
    public Set<ApartmentAttributeTypeName> getApartmentAttributeTypeNames() {
        return this.apartmentAttributeTypeNames;
    }
    
    public void setApartmentAttributeTypeNames(Set<ApartmentAttributeTypeName> apartmentAttributeTypeNames) {
        this.apartmentAttributeTypeNames = apartmentAttributeTypeNames;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="apartmentAttributeType")
    public Set<ApartmentAttribute> getApartmentAttributes() {
        return this.apartmentAttributes;
    }
    
    public void setApartmentAttributes(Set<ApartmentAttribute> apartmentAttributes) {
        this.apartmentAttributes = apartmentAttributes;
    }




}


