package org.flexpay.bti.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


/**
 * ActFilesId generated by hbm2java
 */
public class ActFilesId implements java.io.Serializable {


	private int id;
	private int actId;
	private String fileName;
	private int fileOrder;

	public ActFilesId() {
	}

	public ActFilesId(int id, int actId, String fileName, int fileOrder) {
		this.id = id;
		this.actId = actId;
		this.fileName = fileName;
		this.fileOrder = fileOrder;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getActId() {
		return this.actId;
	}

	public void setActId(int actId) {
		this.actId = actId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public int getFileOrder() {
		return this.fileOrder;
	}

	public void setFileOrder(int fileOrder) {
		this.fileOrder = fileOrder;
	}

}


