package org.flexpay.bti.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Act generated by hbm2java
 */
/*
@Entity
@Table (name = "act"
		, catalog = "flexpay_db"
)
*/
public class Act implements java.io.Serializable {


	private int id;
	private String name;
	private Date creationDate;
	private Set<Personact> personacts = new HashSet<Personact>(0);
	private Set<ApartmentRelation> apartmentRelations = new HashSet<ApartmentRelation>(0);
	private Set<ActFiles> actFileses = new HashSet<ActFiles>(0);

	public Act() {
	}


	public Act(int id, String name, Date creationDate) {
		this.id = id;
		this.name = name;
		this.creationDate = creationDate;
	}

	public Act(int id, String name, Date creationDate, Set<Personact> personacts, Set<ApartmentRelation> apartmentRelations, Set<ActFiles> actFileses) {
		this.id = id;
		this.name = name;
		this.creationDate = creationDate;
		this.personacts = personacts;
		this.apartmentRelations = apartmentRelations;
		this.actFileses = actFileses;
	}

	@Id

	@Column (name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "name", nullable = false, length = 4000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "creation_date", nullable = false, length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany (fetch = FetchType.LAZY, mappedBy = "act")
	public Set<Personact> getPersonacts() {
		return this.personacts;
	}

	public void setPersonacts(Set<Personact> personacts) {
		this.personacts = personacts;
	}

	@ManyToMany (fetch = FetchType.LAZY)
	public Set<ApartmentRelation> getApartmentRelations() {
		return this.apartmentRelations;
	}

	public void setApartmentRelations(Set<ApartmentRelation> apartmentRelations) {
		this.apartmentRelations = apartmentRelations;
	}

	@OneToMany (fetch = FetchType.LAZY, mappedBy = "act")
	public Set<ActFiles> getActFileses() {
		return this.actFileses;
	}

	public void setActFileses(Set<ActFiles> actFileses) {
		this.actFileses = actFileses;
	}

}


