package org.flexpay.bti.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActFilesId generated by hbm2java
 */
@Embeddable
public class ActFilesId implements java.io.Serializable {


	private int id;
	private int actId;
	private String fileName;
	private int fileOrder;

	public ActFilesId() {
	}

	public ActFilesId(int id, int actId, String fileName, int fileOrder) {
		this.id = id;
		this.actId = actId;
		this.fileName = fileName;
		this.fileOrder = fileOrder;
	}


	@Column (name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "Act_ID", nullable = false)
	public int getActId() {
		return this.actId;
	}

	public void setActId(int actId) {
		this.actId = actId;
	}

	@Column (name = "FileName", nullable = false, length = 4000)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column (name = "file_order", nullable = false)
	public int getFileOrder() {
		return this.fileOrder;
	}

	public void setFileOrder(int fileOrder) {
		this.fileOrder = fileOrder;
	}

}


