package org.flexpay.bti.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Acts generated by hbm2java
 */
/*
@Entity
@Table (name = "acts", catalog = "flexpay_db")
*/
public class Acts implements Serializable {

	// Fields

	private ActsId id;
	private ApartmentRelation apartmentRelation;
	private Act act;

	// Constructors

	/**
	 * default constructor
	 */
	public Acts() {
	}

	/**
	 * full constructor
	 */
	public Acts(ActsId id, ApartmentRelation apartmentRelation, Act act) {
		this.id = id;
		this.apartmentRelation = apartmentRelation;
		this.act = act;
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides ({
	@AttributeOverride (
			name = "apartmentRelationId",
			column = @Column (
					name = "Apartment_Relation_ID", unique = false, nullable = false, insertable = true, updatable = true)),
	@AttributeOverride (
			name = "actId",
			column = @Column (
					name = "Act_ID", unique = false, nullable = false, insertable = true, updatable = true))})
	public ActsId getId() {
		return this.id;
	}

	public void setId(ActsId id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Apartment_Relation_ID", unique = false, nullable = false, insertable = false, updatable = false)
	public ApartmentRelation getApartmentRelation() {
		return this.apartmentRelation;
	}

	public void setApartmentRelation(ApartmentRelation apartmentRelation) {
		this.apartmentRelation = apartmentRelation;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Act_ID", unique = false, nullable = false, insertable = false, updatable = false)
	public Act getAct() {
		return this.act;
	}

	public void setAct(Act act) {
		this.act = act;
	}

}


