package org.flexpay.bti.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.*;

/**
 * ApartmentAttributeTypeName generated by hbm2java
 */
@Entity
@Table (name = "apartment_attribute_type_name"
		, catalog = "flexpay_db"
)
public class ApartmentAttributeTypeName implements java.io.Serializable {


	private int id;
	private ApartmentAttributeType apartmentAttributeType;
	private String name;
	private String lang;

	public ApartmentAttributeTypeName() {
	}

	public ApartmentAttributeTypeName(int id, ApartmentAttributeType apartmentAttributeType, String name, String lang) {
		this.id = id;
		this.apartmentAttributeType = apartmentAttributeType;
		this.name = name;
		this.lang = lang;
	}

	@Id

	@Column (name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Apartment_Attribute_Type_ID", nullable = false)
	public ApartmentAttributeType getApartmentAttributeType() {
		return this.apartmentAttributeType;
	}

	public void setApartmentAttributeType(ApartmentAttributeType apartmentAttributeType) {
		this.apartmentAttributeType = apartmentAttributeType;
	}

	@Column (name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", nullable = false)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


