package org.flexpay.bti.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
/*
@Entity
@Table (name = "room"
		, catalog = "flexpay_db"
)
*/
public class Room implements java.io.Serializable {


	private int id;
	private int roomTypeId;
	private char status;
	private Set<Rooms> roomses = new HashSet<Rooms>(0);
	private Set<RoomAttribute> roomAttributes = new HashSet<RoomAttribute>(0);

	public Room() {
	}


	public Room(int id, int roomTypeId, char status) {
		this.id = id;
		this.roomTypeId = roomTypeId;
		this.status = status;
	}

	public Room(int id, int roomTypeId, char status, Set<Rooms> roomses, Set<RoomAttribute> roomAttributes) {
		this.id = id;
		this.roomTypeId = roomTypeId;
		this.status = status;
		this.roomses = roomses;
		this.roomAttributes = roomAttributes;
	}

	@Id

	@Column (name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "room_type_ID", nullable = false)
	public int getRoomTypeId() {
		return this.roomTypeId;
	}

	public void setRoomTypeId(int roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	@Column (name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany (fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Rooms> getRoomses() {
		return this.roomses;
	}

	public void setRoomses(Set<Rooms> roomses) {
		this.roomses = roomses;
	}

	@OneToMany (fetch = FetchType.LAZY, mappedBy = "room")
	public Set<RoomAttribute> getRoomAttributes() {
		return this.roomAttributes;
	}

	public void setRoomAttributes(Set<RoomAttribute> roomAttributes) {
		this.roomAttributes = roomAttributes;
	}

}


