package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ApartmentRelationType generated by hbm2java
 */
@Entity
@Table (name = "apartment_relation_type", catalog = "flexpay_db")
public class ApartmentRelationType implements Serializable {

	// Fields

	private int id;
	private String name;
	private Set<ApartmentRelation> apartmentRelations = new HashSet<ApartmentRelation>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public ApartmentRelationType() {
	}

	/**
	 * minimal constructor
	 */
	public ApartmentRelationType(int id, String name) {
		this.id = id;
		this.name = name;
	}

	/**
	 * full constructor
	 */
	public ApartmentRelationType(int id, String name, Set<ApartmentRelation> apartmentRelations) {
		this.id = id;
		this.name = name;
		this.apartmentRelations = apartmentRelations;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "Name", unique = false, nullable = false, insertable = true, updatable = true, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "apartmentRelationType")
	public Set<ApartmentRelation> getApartmentRelations() {
		return this.apartmentRelations;
	}

	public void setApartmentRelations(Set<ApartmentRelation> apartmentRelations) {
		this.apartmentRelations = apartmentRelations;
	}

}


