package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * BuildingAttributeTypeLang generated by hbm2java
 */
@Entity
@Table (name = "building_attribute_type_lang", catalog = "flexpay_db")
public class BuildingAttributeTypeLang implements Serializable {

	// Fields

	private int id;
	private BuildingAttributeType buildingAttributeType;
	private String name;
	private String lang;
	private String shortName;

	// Constructors

	/**
	 * default constructor
	 */
	public BuildingAttributeTypeLang() {
	}

	/**
	 * full constructor
	 */
	public BuildingAttributeTypeLang(int id, BuildingAttributeType buildingAttributeType, String name, String lang, String shortName) {
		this.id = id;
		this.buildingAttributeType = buildingAttributeType;
		this.name = name;
		this.lang = lang;
		this.shortName = shortName;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Building_Attribute_Type_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public BuildingAttributeType getBuildingAttributeType() {
		return this.buildingAttributeType;
	}

	public void setBuildingAttributeType(BuildingAttributeType buildingAttributeType) {
		this.buildingAttributeType = buildingAttributeType;
	}

	@Column (name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column (name = "short_name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

}


