package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name="building"
    ,catalog="flexpay_db"
)
public class Building  implements java.io.Serializable {


     private int id;
     private District district;
     private int buildingStatus;
     private Set<BuildingStatus> buildingStatuses = new HashSet<BuildingStatus>(0);
     private Set<Buildings> buildingses = new HashSet<Buildings>(0);
     private Set<Apartment> apartments = new HashSet<Apartment>(0);

    public Building() {
    }

	
    public Building(int id, District district, int buildingStatus) {
        this.id = id;
        this.district = district;
        this.buildingStatus = buildingStatus;
    }
    public Building(int id, District district, int buildingStatus, Set<BuildingStatus> buildingStatuses, Set<Buildings> buildingses, Set<Apartment> apartments) {
       this.id = id;
       this.district = district;
       this.buildingStatus = buildingStatus;
       this.buildingStatuses = buildingStatuses;
       this.buildingses = buildingses;
       this.apartments = apartments;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="District_ID", nullable=false)
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    
    @Column(name="Building_Status", nullable=false)
    public int getBuildingStatus() {
        return this.buildingStatus;
    }
    
    public void setBuildingStatus(int buildingStatus) {
        this.buildingStatus = buildingStatus;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="building")
    public Set<BuildingStatus> getBuildingStatuses() {
        return this.buildingStatuses;
    }
    
    public void setBuildingStatuses(Set<BuildingStatus> buildingStatuses) {
        this.buildingStatuses = buildingStatuses;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="building")
    public Set<Buildings> getBuildingses() {
        return this.buildingses;
    }
    
    public void setBuildingses(Set<Buildings> buildingses) {
        this.buildingses = buildingses;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="building")
    public Set<Apartment> getApartments() {
        return this.apartments;
    }
    
    public void setApartments(Set<Apartment> apartments) {
        this.apartments = apartments;
    }




}


