package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuildingAttributeType generated by hbm2java
 */
@Entity
@Table(name="building_attribute_type"
    ,catalog="flexpay_db"
)
public class BuildingAttributeType  implements java.io.Serializable {


     private int id;
     private Set<BuildingAttribute> buildingAttributes = new HashSet<BuildingAttribute>(0);
     private Set<BuildingAttributeTypeLang> buildingAttributeTypeLangs = new HashSet<BuildingAttributeTypeLang>(0);

    public BuildingAttributeType() {
    }

	
    public BuildingAttributeType(int id) {
        this.id = id;
    }
    public BuildingAttributeType(int id, Set<BuildingAttribute> buildingAttributes, Set<BuildingAttributeTypeLang> buildingAttributeTypeLangs) {
       this.id = id;
       this.buildingAttributes = buildingAttributes;
       this.buildingAttributeTypeLangs = buildingAttributeTypeLangs;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="buildingAttributeType")
    public Set<BuildingAttribute> getBuildingAttributes() {
        return this.buildingAttributes;
    }
    
    public void setBuildingAttributes(Set<BuildingAttribute> buildingAttributes) {
        this.buildingAttributes = buildingAttributes;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="buildingAttributeType")
    public Set<BuildingAttributeTypeLang> getBuildingAttributeTypeLangs() {
        return this.buildingAttributeTypeLangs;
    }
    
    public void setBuildingAttributeTypeLangs(Set<BuildingAttributeTypeLang> buildingAttributeTypeLangs) {
        this.buildingAttributeTypeLangs = buildingAttributeTypeLangs;
    }




}


