package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DistrictName generated by hbm2java
 */
@Entity
@Table(name="district_name"
    ,catalog="flexpay_db"
)
public class DistrictName  implements java.io.Serializable {


     private int id;
     private District district;
     private Date begin;
     private Date end;
     private Set<DistrictNameLangValue> districtNameLangValues = new HashSet<DistrictNameLangValue>(0);

    public DistrictName() {
    }

	
    public DistrictName(int id, District district, Date begin, Date end) {
        this.id = id;
        this.district = district;
        this.begin = begin;
        this.end = end;
    }
    public DistrictName(int id, District district, Date begin, Date end, Set<DistrictNameLangValue> districtNameLangValues) {
       this.id = id;
       this.district = district;
       this.begin = begin;
       this.end = end;
       this.districtNameLangValues = districtNameLangValues;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="District_ID", nullable=false)
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    
    @Column(name="begin", nullable=false, length=0)
    public Date getBegin() {
        return this.begin;
    }
    
    public void setBegin(Date begin) {
        this.begin = begin;
    }
    
    @Column(name="end", nullable=false, length=0)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="districtName")
    public Set<DistrictNameLangValue> getDistrictNameLangValues() {
        return this.districtNameLangValues;
    }
    
    public void setDistrictNameLangValues(Set<DistrictNameLangValue> districtNameLangValues) {
        this.districtNameLangValues = districtNameLangValues;
    }




}


