package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DistrictName generated by hbm2java
 */
@Entity
@Table (name = "district_name", catalog = "flexpay_db")
public class DistrictName implements Serializable {

	// Fields

	private int id;
	private District district;
	private Date begin;
	private Date end;
	private Set<DistrictNameLangValue> districtNameLangValues = new HashSet<DistrictNameLangValue>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public DistrictName() {
	}

	/**
	 * minimal constructor
	 */
	public DistrictName(int id, District district, Date begin, Date end) {
		this.id = id;
		this.district = district;
		this.begin = begin;
		this.end = end;
	}

	/**
	 * full constructor
	 */
	public DistrictName(int id, District district, Date begin, Date end, Set<DistrictNameLangValue> districtNameLangValues) {
		this.id = id;
		this.district = district;
		this.begin = begin;
		this.end = end;
		this.districtNameLangValues = districtNameLangValues;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "District_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "districtName")
	public Set<DistrictNameLangValue> getDistrictNameLangValues() {
		return this.districtNameLangValues;
	}

	public void setDistrictNameLangValues(Set<DistrictNameLangValue> districtNameLangValues) {
		this.districtNameLangValues = districtNameLangValues;
	}

}


