package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name="history"
    ,catalog="flexpay_db"
)
public class History  implements java.io.Serializable {


     private int id;
     private History history;
     private Date recordDate;
     private String actionType;
     private String value;
     private String oldValue;
     private Set<History> histories = new HashSet<History>(0);

    public History() {
    }

	
    public History(int id, Date recordDate, String actionType, String value) {
        this.id = id;
        this.recordDate = recordDate;
        this.actionType = actionType;
        this.value = value;
    }
    public History(int id, History history, Date recordDate, String actionType, String value, String oldValue, Set<History> histories) {
       this.id = id;
       this.history = history;
       this.recordDate = recordDate;
       this.actionType = actionType;
       this.value = value;
       this.oldValue = oldValue;
       this.histories = histories;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="History_ID")
    public History getHistory() {
        return this.history;
    }
    
    public void setHistory(History history) {
        this.history = history;
    }
    
    @Column(name="record_date", nullable=false, length=0)
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
    
    @Column(name="action_type", nullable=false)
    public String getActionType() {
        return this.actionType;
    }
    
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }
    
    @Column(name="value", nullable=false, length=4000)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="old_value", length=4000)
    public String getOldValue() {
        return this.oldValue;
    }
    
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="history")
    public Set<History> getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set<History> histories) {
        this.histories = histories;
    }




}


