package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import org.flexpay.common.persistence.AttributeTranslation;

/**
 * PersonAttribute generated by hbm2java
 */
public class PersonAttribute extends AttributeTranslation {

	public PersonAttribute() {
	}
}
