package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * PersonAttribute generated by hbm2java
 */
@Entity
@Table (name = "person_attribute", catalog = "flexpay_db")
public class PersonAttribute implements Serializable {

	// Fields

	private int id;
	private Person person;
	private String value;
	private String name;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public PersonAttribute() {
	}

	/**
	 * full constructor
	 */
	public PersonAttribute(int id, Person person, String value, String name, String lang) {
		this.id = id;
		this.person = person;
		this.value = value;
		this.name = name;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Person_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column (name = "VALUE", unique = false, nullable = false, insertable = true, updatable = true, length = 4000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column (name = "NAME", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


