package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
@Entity
@Table (name = "region", catalog = "flexpay_db")
public class Region implements Serializable {

	// Fields

	private int id;
	private Country country;
	private int regionStatus;
	private String regionShortName;
	private Set<RegionName> regionNames = new HashSet<RegionName>(0);
	private Set<Town> towns = new HashSet<Town>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public Region() {
	}

	/**
	 * minimal constructor
	 */
	public Region(int id, Country country, int regionStatus, String regionShortName) {
		this.id = id;
		this.country = country;
		this.regionStatus = regionStatus;
		this.regionShortName = regionShortName;
	}

	/**
	 * full constructor
	 */
	public Region(int id, Country country, int regionStatus, String regionShortName, Set<RegionName> regionNames, Set<Town> towns) {
		this.id = id;
		this.country = country;
		this.regionStatus = regionStatus;
		this.regionShortName = regionShortName;
		this.regionNames = regionNames;
		this.towns = towns;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Country_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column (name = "Region_Status", unique = false, nullable = false, insertable = true, updatable = true)
	public int getRegionStatus() {
		return this.regionStatus;
	}

	public void setRegionStatus(int regionStatus) {
		this.regionStatus = regionStatus;
	}

	@Column (name = "Region_Short_Name", unique = false, nullable = false, insertable = true, updatable = true, length = 200)
	public String getRegionShortName() {
		return this.regionShortName;
	}

	public void setRegionShortName(String regionShortName) {
		this.regionShortName = regionShortName;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "region")
	public Set<RegionName> getRegionNames() {
		return this.regionNames;
	}

	public void setRegionNames(Set<RegionName> regionNames) {
		this.regionNames = regionNames;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Town> getTowns() {
		return this.towns;
	}

	public void setTowns(Set<Town> towns) {
		this.towns = towns;
	}

}


