package org.flexpay.ab.persistence;

import java.util.Collections;
import java.util.Date;
import java.util.Set;

/**
 * RegionName generated by hbm2java
 */
public class RegionName implements java.io.Serializable {

	private Long id;
	private Region region;
	private Date begin;
	private Date end;
	private Set<RegionNameTranslation> translations = Collections.emptySet();

	private transient RegionNameTranslation translation;

	/** Constructs a new RegionName. */
	public RegionName() {
	}

	/**
	 * Getter for property 'id'.
	 *
	 * @return Value for property 'id'.
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Setter for property 'id'.
	 *
	 * @param id Value to set for property 'id'.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Getter for property 'region'.
	 *
	 * @return Value for property 'region'.
	 */
	public Region getRegion() {
		return this.region;
	}

	/**
	 * Setter for property 'region'.
	 *
	 * @param region Value to set for property 'region'.
	 */
	public void setRegion(Region region) {
		this.region = region;
	}

	/**
	 * Getter for property 'begin'.
	 *
	 * @return Value for property 'begin'.
	 */
	public Date getBegin() {
		return this.begin;
	}

	/**
	 * Setter for property 'begin'.
	 *
	 * @param begin Value to set for property 'begin'.
	 */
	public void setBegin(Date begin) {
		this.begin = begin;
	}

	/**
	 * Getter for property 'end'.
	 *
	 * @return Value for property 'end'.
	 */
	public Date getEnd() {
		return this.end;
	}

	/**
	 * Setter for property 'end'.
	 *
	 * @param end Value to set for property 'end'.
	 */
	public void setEnd(Date end) {
		this.end = end;
	}

	/**
	 * Getter for property 'translations'.
	 *
	 * @return Value for property 'translations'.
	 */
	public Set<RegionNameTranslation> getTranslations() {
		return translations;
	}

	/**
	 * Setter for property 'translations'.
	 *
	 * @param translations Value to set for property 'translations'.
	 */
	public void setTranslations(Set<RegionNameTranslation> translations) {
		this.translations = translations;
	}

	/**
	 * Get transient property 'translation'.
	 *
	 * @return Value for property 'translation'.
	 */
	public RegionNameTranslation getTranslation() {
		return translation;
	}

	/**
	 * Setter for property 'translation'.
	 *
	 * @param translation Value to set for property 'translation'.
	 */
	public void setTranslation(RegionNameTranslation translation) {
		this.translation = translation;
	}
}
