package org.flexpay.ab.persistence;

import org.flexpay.common.persistence.Language;

/**
 * RegionNameLangValue generated by hbm2java
 */
public class RegionNameTranslation implements java.io.Serializable {

	private Long id;
	private String name;
	private RegionName regionName;
	private Language lang;

	/** Constructs a new RegionNameTranslation. */
	public RegionNameTranslation() {
	}

	/**
	 * Getter for property 'id'.
	 *
	 * @return Value for property 'id'.
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Setter for property 'id'.
	 *
	 * @param id Value to set for property 'id'.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Getter for property 'regionName'.
	 *
	 * @return Value for property 'regionName'.
	 */
	public RegionName getRegionName() {
		return regionName;
	}

	/**
	 * Setter for property 'regionName'.
	 *
	 * @param regionName Value to set for property 'regionName'.
	 */
	public void setRegionName(RegionName regionName) {
		this.regionName = regionName;
	}

	/**
	 * Getter for property 'name'.
	 *
	 * @return Value for property 'name'.
	 */
	public String getName() {
		return name;
	}

	/**
	 * Setter for property 'name'.
	 *
	 * @param name Value to set for property 'name'.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Getter for property 'lang'.
	 *
	 * @return Value for property 'lang'.
	 */
	public Language getLang() {
		return lang;
	}

	/**
	 * Setter for property 'lang'.
	 *
	 * @param lang Value to set for property 'lang'.
	 */
	public void setLang(Language lang) {
		this.lang = lang;
	}
}
