package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
@Entity
@Table (name = "room", catalog = "flexpay_db")
public class Room implements Serializable {

	// Fields

	private int id;
	private int roomTypeId;
	private char status;
	private Set<Rooms> roomses = new HashSet<Rooms>(0);
	private Set<RoomAttribute> roomAttributes = new HashSet<RoomAttribute>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public Room() {
	}

	/**
	 * minimal constructor
	 */
	public Room(int id, int roomTypeId, char status) {
		this.id = id;
		this.roomTypeId = roomTypeId;
		this.status = status;
	}

	/**
	 * full constructor
	 */
	public Room(int id, int roomTypeId, char status, Set<Rooms> roomses, Set<RoomAttribute> roomAttributes) {
		this.id = id;
		this.roomTypeId = roomTypeId;
		this.status = status;
		this.roomses = roomses;
		this.roomAttributes = roomAttributes;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "room_type_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getRoomTypeId() {
		return this.roomTypeId;
	}

	public void setRoomTypeId(int roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	@Column (name = "status", unique = false, nullable = false, insertable = true, updatable = true, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Rooms> getRoomses() {
		return this.roomses;
	}

	public void setRoomses(Set<Rooms> roomses) {
		this.roomses = roomses;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "room")
	public Set<RoomAttribute> getRoomAttributes() {
		return this.roomAttributes;
	}

	public void setRoomAttributes(Set<RoomAttribute> roomAttributes) {
		this.roomAttributes = roomAttributes;
	}

}


