package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Rooms generated by hbm2java
 */
@Entity
@Table (name = "rooms", catalog = "flexpay_db")
public class Rooms implements Serializable {

	// Fields

	private int id;
	private Room room;
	private Apartment apartment;
	private int roomId;

	// Constructors

	/**
	 * default constructor
	 */
	public Rooms() {
	}

	/**
	 * full constructor
	 */
	public Rooms(int id, Room room, Apartment apartment, int roomId) {
		this.id = id;
		this.room = room;
		this.apartment = apartment;
		this.roomId = roomId;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "id", unique = true, nullable = false, insertable = false, updatable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Apartment_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Apartment getApartment() {
		return this.apartment;
	}

	public void setApartment(Apartment apartment) {
		this.apartment = apartment;
	}

	@Column (name = "Room_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

}


