package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * StreetTypes generated by hbm2java
 */
@Entity
@Table (name = "street_types", catalog = "flexpay_db")
public class StreetTypes implements Serializable {

	// Fields

	private int id;
	private String name;
	private String lang;
	private Set<StreetType> streetTypes = new HashSet<StreetType>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public StreetTypes() {
	}

	/**
	 * minimal constructor
	 */
	public StreetTypes(int id, String name, String lang) {
		this.id = id;
		this.name = name;
		this.lang = lang;
	}

	/**
	 * full constructor
	 */
	public StreetTypes(int id, String name, String lang, Set<StreetType> streetTypes) {
		this.id = id;
		this.name = name;
		this.lang = lang;
		this.streetTypes = streetTypes;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "Name", unique = false, nullable = false, insertable = true, updatable = true, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "streetTypes")
	public Set<StreetType> getStreetTypes() {
		return this.streetTypes;
	}

	public void setStreetTypes(Set<StreetType> streetTypes) {
		this.streetTypes = streetTypes;
	}

}


