package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StreetName generated by hbm2java
 */
@Entity
@Table (name = "street_name", catalog = "flexpay_db")
public class StreetName implements Serializable {

	// Fields

	private int id;
	private Street street;
	private Date begin;
	private Date end;
	private Set<StreetNameLangValue> streetNameLangValues = new HashSet<StreetNameLangValue>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public StreetName() {
	}

	/**
	 * minimal constructor
	 */
	public StreetName(int id, Street street, Date begin, Date end) {
		this.id = id;
		this.street = street;
		this.begin = begin;
		this.end = end;
	}

	/**
	 * full constructor
	 */
	public StreetName(int id, Street street, Date begin, Date end, Set<StreetNameLangValue> streetNameLangValues) {
		this.id = id;
		this.street = street;
		this.begin = begin;
		this.end = end;
		this.streetNameLangValues = streetNameLangValues;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Street_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Street getStreet() {
		return this.street;
	}

	public void setStreet(Street street) {
		this.street = street;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "streetName")
	public Set<StreetNameLangValue> getStreetNameLangValues() {
		return this.streetNameLangValues;
	}

	public void setStreetNameLangValues(Set<StreetNameLangValue> streetNameLangValues) {
		this.streetNameLangValues = streetNameLangValues;
	}

}


