package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * TownNameLangValue generated by hbm2java
 */
@Entity
@Table (name = "town_name_lang_value", catalog = "flexpay_db")
public class TownNameLangValue implements Serializable {

	// Fields

	private int id;
	private TownName townName;
	private String value;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public TownNameLangValue() {
	}

	/**
	 * full constructor
	 */
	public TownNameLangValue(int id, TownName townName, String value, String lang) {
		this.id = id;
		this.townName = townName;
		this.value = value;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "TownName_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public TownName getTownName() {
		return this.townName;
	}

	public void setTownName(TownName townName) {
		this.townName = townName;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


