package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Town generated by hbm2java
 */
@Entity
@Table(name="town"
    ,catalog="flexpay_db"
)
public class Town  implements java.io.Serializable {


     private int id;
     private TownType townType;
     private Region region;
     private int townStatus;
     private Set<TownName> townNames = new HashSet<TownName>(0);
     private Set<District> districts = new HashSet<District>(0);
     private Set<Street> streets = new HashSet<Street>(0);

    public Town() {
    }

	
    public Town(int id, Region region, int townStatus) {
        this.id = id;
        this.region = region;
        this.townStatus = townStatus;
    }
    public Town(int id, TownType townType, Region region, int townStatus, Set<TownName> townNames, Set<District> districts, Set<Street> streets) {
       this.id = id;
       this.townType = townType;
       this.region = region;
       this.townStatus = townStatus;
       this.townNames = townNames;
       this.districts = districts;
       this.streets = streets;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Town_Type_id")
    public TownType getTownType() {
        return this.townType;
    }
    
    public void setTownType(TownType townType) {
        this.townType = townType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Region_ID", nullable=false)
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    
    @Column(name="Town_Status", nullable=false)
    public int getTownStatus() {
        return this.townStatus;
    }
    
    public void setTownStatus(int townStatus) {
        this.townStatus = townStatus;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="town")
    public Set<TownName> getTownNames() {
        return this.townNames;
    }
    
    public void setTownNames(Set<TownName> townNames) {
        this.townNames = townNames;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="town")
    public Set<District> getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set<District> districts) {
        this.districts = districts;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="town")
    public Set<Street> getStreets() {
        return this.streets;
    }
    
    public void setStreets(Set<Street> streets) {
        this.streets = streets;
    }




}


