package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TownNameLangValue generated by hbm2java
 */
@Entity
@Table(name="town_name_lang_value"
    ,catalog="flexpay_db"
)
public class TownNameLangValue  implements java.io.Serializable {


     private int id;
     private TownName townName;
     private String value;
     private String lang;

    public TownNameLangValue() {
    }

    public TownNameLangValue(int id, TownName townName, String value, String lang) {
       this.id = id;
       this.townName = townName;
       this.value = value;
       this.lang = lang;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TownName_ID", nullable=false)
    public TownName getTownName() {
        return this.townName;
    }
    
    public void setTownName(TownName townName) {
        this.townName = townName;
    }
    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="LANG", nullable=false)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }




}


