package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TownType generated by hbm2java
 */
@Entity
@Table (name = "town_type", catalog = "flexpay_db")
public class TownType implements Serializable {

	// Fields

	private int id;
	private TownTypes townTypes;
	private int townTypeId;
	private Date begin;
	private Date end;
	private Set<Town> towns = new HashSet<Town>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public TownType() {
	}

	/**
	 * minimal constructor
	 */
	public TownType(int id, TownTypes townTypes, int townTypeId, Date begin, Date end) {
		this.id = id;
		this.townTypes = townTypes;
		this.townTypeId = townTypeId;
		this.begin = begin;
		this.end = end;
	}

	/**
	 * full constructor
	 */
	public TownType(int id, TownTypes townTypes, int townTypeId, Date begin, Date end, Set<Town> towns) {
		this.id = id;
		this.townTypes = townTypes;
		this.townTypeId = townTypeId;
		this.begin = begin;
		this.end = end;
		this.towns = towns;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "id", unique = true, nullable = false, insertable = false, updatable = false)
	public TownTypes getTownTypes() {
		return this.townTypes;
	}

	public void setTownTypes(TownTypes townTypes) {
		this.townTypes = townTypes;
	}

	@Column (name = "TownType_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getTownTypeId() {
		return this.townTypeId;
	}

	public void setTownTypeId(int townTypeId) {
		this.townTypeId = townTypeId;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "townType")
	public Set<Town> getTowns() {
		return this.towns;
	}

	public void setTowns(Set<Town> towns) {
		this.towns = towns;
	}

}


