package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TownName generated by hbm2java
 */
@Entity
@Table (name = "town_name", catalog = "flexpay_db")
public class TownName implements Serializable {

	// Fields

	private int id;
	private Town town;
	private Date begin;
	private Date end;
	private int townId;
	private Set<TownNameLangValue> townNameLangValues = new HashSet<TownNameLangValue>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public TownName() {
	}

	/**
	 * minimal constructor
	 */
	public TownName(int id, Town town, Date begin, Date end, int townId) {
		this.id = id;
		this.town = town;
		this.begin = begin;
		this.end = end;
		this.townId = townId;
	}

	/**
	 * full constructor
	 */
	public TownName(int id, Town town, Date begin, Date end, int townId, Set<TownNameLangValue> townNameLangValues) {
		this.id = id;
		this.town = town;
		this.begin = begin;
		this.end = end;
		this.townId = townId;
		this.townNameLangValues = townNameLangValues;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "ID", unique = true, nullable = false, insertable = false, updatable = false)
	public Town getTown() {
		return this.town;
	}

	public void setTown(Town town) {
		this.town = town;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column (name = "Town_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getTownId() {
		return this.townId;
	}

	public void setTownId(int townId) {
		this.townId = townId;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "townName")
	public Set<TownNameLangValue> getTownNameLangValues() {
		return this.townNameLangValues;
	}

	public void setTownNameLangValues(Set<TownNameLangValue> townNameLangValues) {
		this.townNameLangValues = townNameLangValues;
	}

}


