package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TownType generated by hbm2java
 */
@Entity
@Table(name="town_type"
    ,catalog="flexpay_db"
)
public class TownType  implements java.io.Serializable {


     private int id;
     private TownTypes townTypes;
     private int townTypeId;
     private Date begin;
     private Date end;
     private Set<Town> towns = new HashSet<Town>(0);

    public TownType() {
    }

	
    public TownType(int id, TownTypes townTypes, int townTypeId, Date begin, Date end) {
        this.id = id;
        this.townTypes = townTypes;
        this.townTypeId = townTypeId;
        this.begin = begin;
        this.end = end;
    }
    public TownType(int id, TownTypes townTypes, int townTypeId, Date begin, Date end, Set<Town> towns) {
       this.id = id;
       this.townTypes = townTypes;
       this.townTypeId = townTypeId;
       this.begin = begin;
       this.end = end;
       this.towns = towns;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", unique=true, nullable=false, insertable=false, updatable=false)
    public TownTypes getTownTypes() {
        return this.townTypes;
    }
    
    public void setTownTypes(TownTypes townTypes) {
        this.townTypes = townTypes;
    }
    
    @Column(name="TownType_ID", nullable=false)
    public int getTownTypeId() {
        return this.townTypeId;
    }
    
    public void setTownTypeId(int townTypeId) {
        this.townTypeId = townTypeId;
    }
    
    @Column(name="begin", nullable=false, length=0)
    public Date getBegin() {
        return this.begin;
    }
    
    public void setBegin(Date begin) {
        this.begin = begin;
    }
    
    @Column(name="end", nullable=false, length=0)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="townType")
    public Set<Town> getTowns() {
        return this.towns;
    }
    
    public void setTowns(Set<Town> towns) {
        this.towns = towns;
    }




}


