package org.flexpay.ab.persistence.temp;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingAttributeTypeLang generated by hbm2java
 */
@Entity
@Table(name="building_attribute_type_lang"
    ,catalog="flexpay_db"
)
public class BuildingAttributeTypeLang  implements java.io.Serializable {


     private int id;
     private BuildingAttributeType buildingAttributeType;
     private String name;
     private String lang;
     private String shortName;

    public BuildingAttributeTypeLang() {
    }

    public BuildingAttributeTypeLang(int id, BuildingAttributeType buildingAttributeType, String name, String lang, String shortName) {
       this.id = id;
       this.buildingAttributeType = buildingAttributeType;
       this.name = name;
       this.lang = lang;
       this.shortName = shortName;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Building_Attribute_Type_ID", nullable=false)
    public BuildingAttributeType getBuildingAttributeType() {
        return this.buildingAttributeType;
    }
    
    public void setBuildingAttributeType(BuildingAttributeType buildingAttributeType) {
        this.buildingAttributeType = buildingAttributeType;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="LANG", nullable=false)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
    
    @Column(name="short_name", nullable=false)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }




}


