package org.flexpay.ab.persistence.temp;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DistrictNameLangValue generated by hbm2java
 */
@Entity
@Table(name="district_name_lang_value"
    ,catalog="flexpay_db"
)
public class DistrictNameLangValue  implements java.io.Serializable {


     private int id;
     private DistrictName districtName;
     private String value;
     private String lang;

    public DistrictNameLangValue() {
    }

    public DistrictNameLangValue(int id, DistrictName districtName, String value, String lang) {
       this.id = id;
       this.districtName = districtName;
       this.value = value;
       this.lang = lang;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DistrictName_ID", nullable=false)
    public DistrictName getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(DistrictName districtName) {
        this.districtName = districtName;
    }
    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="LANG", nullable=false)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }




}


