package org.flexpay.ab.persistence.temp;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TownName generated by hbm2java
 */
@Entity
@Table(name="town_name"
    ,catalog="flexpay_db"
)
public class TownName  implements java.io.Serializable {


     private int id;
     private Town town;
     private Date begin;
     private Date end;
     private int townId;
     private Set<TownNameLangValue> townNameLangValues = new HashSet<TownNameLangValue>(0);

    public TownName() {
    }

	
    public TownName(int id, Town town, Date begin, Date end, int townId) {
        this.id = id;
        this.town = town;
        this.begin = begin;
        this.end = end;
        this.townId = townId;
    }
    public TownName(int id, Town town, Date begin, Date end, int townId, Set<TownNameLangValue> townNameLangValues) {
       this.id = id;
       this.town = town;
       this.begin = begin;
       this.end = end;
       this.townId = townId;
       this.townNameLangValues = townNameLangValues;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID", unique=true, nullable=false, insertable=false, updatable=false)
    public Town getTown() {
        return this.town;
    }
    
    public void setTown(Town town) {
        this.town = town;
    }
    
    @Column(name="begin", nullable=false, length=0)
    public Date getBegin() {
        return this.begin;
    }
    
    public void setBegin(Date begin) {
        this.begin = begin;
    }
    
    @Column(name="end", nullable=false, length=0)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    
    @Column(name="Town_ID", nullable=false)
    public int getTownId() {
        return this.townId;
    }
    
    public void setTownId(int townId) {
        this.townId = townId;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="townName")
    public Set<TownNameLangValue> getTownNameLangValues() {
        return this.townNameLangValues;
    }
    
    public void setTownNameLangValues(Set<TownNameLangValue> townNameLangValues) {
        this.townNameLangValues = townNameLangValues;
    }




}


