package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Act generated by hbm2java
 */
@Entity
@Table (name = "act", catalog = "flexpay_db")
public class Act implements Serializable {

	// Fields

	private int id;
	private String name;
	private Date creationDate;
	private Set<Personact> personacts = new HashSet<Personact>(0);
	private Set<Acts> actses = new HashSet<Acts>(0);
	private Set<ActFiles> actFileses = new HashSet<ActFiles>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public Act() {
	}

	/**
	 * minimal constructor
	 */
	public Act(int id, String name, Date creationDate) {
		this.id = id;
		this.name = name;
		this.creationDate = creationDate;
	}

	/**
	 * full constructor
	 */
	public Act(int id, String name, Date creationDate, Set<Personact> personacts, Set<Acts> actses, Set<ActFiles> actFileses) {
		this.id = id;
		this.name = name;
		this.creationDate = creationDate;
		this.personacts = personacts;
		this.actses = actses;
		this.actFileses = actFileses;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "name", unique = false, nullable = false, insertable = true, updatable = true, length = 4000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "creation_date", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "act")
	public Set<Personact> getPersonacts() {
		return this.personacts;
	}

	public void setPersonacts(Set<Personact> personacts) {
		this.personacts = personacts;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "act")
	public Set<Acts> getActses() {
		return this.actses;
	}

	public void setActses(Set<Acts> actses) {
		this.actses = actses;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "act")
	public Set<ActFiles> getActFileses() {
		return this.actFileses;
	}

	public void setActFileses(Set<ActFiles> actFileses) {
		this.actFileses = actFileses;
	}

}


