package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * ActFiles generated by hbm2java
 */
@Entity
@Table (name = "act_files", catalog = "flexpay_db")
public class ActFiles implements Serializable {

	// Fields

	private ActFilesId id;
	private Act act;

	// Constructors

	/**
	 * default constructor
	 */
	public ActFiles() {
	}

	/**
	 * full constructor
	 */
	public ActFiles(ActFilesId id, Act act) {
		this.id = id;
		this.act = act;
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides ({@AttributeOverride (name = "id", column = @Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)), @AttributeOverride (name = "actId", column = @Column (name = "Act_ID", unique = false, nullable = false, insertable = true, updatable = true)), @AttributeOverride (name = "fileName", column = @Column (name = "FileName", unique = false, nullable = false, insertable = true, updatable = true, length = 4000)), @AttributeOverride (name = "fileOrder", column = @Column (name = "file_order", unique = false, nullable = false, insertable = true, updatable = true))})
	public ActFilesId getId() {
		return this.id;
	}

	public void setId(ActFilesId id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Act_ID", unique = false, nullable = false, insertable = false, updatable = false)
	public Act getAct() {
		return this.act;
	}

	public void setAct(Act act) {
		this.act = act;
	}

}


