package org.flexpay.ab.persistence;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;

/**
 * ActFilesId generated by hbm2java
 */
@Embeddable
public class ActFilesId implements Serializable {

	// Fields

	private int id;
	private int actId;
	private String fileName;
	private int fileOrder;

	// Constructors

	/**
	 * default constructor
	 */
	public ActFilesId() {
	}

	/**
	 * full constructor
	 */
	public ActFilesId(int id, int actId, String fileName, int fileOrder) {
		this.id = id;
		this.actId = actId;
		this.fileName = fileName;
		this.fileOrder = fileOrder;
	}

	// Property accessors

	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "Act_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getActId() {
		return this.actId;
	}

	public void setActId(int actId) {
		this.actId = actId;
	}

	@Column (name = "FileName", unique = false, nullable = false, insertable = true, updatable = true, length = 4000)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column (name = "file_order", unique = false, nullable = false, insertable = true, updatable = true)
	public int getFileOrder() {
		return this.fileOrder;
	}

	public void setFileOrder(int fileOrder) {
		this.fileOrder = fileOrder;
	}

}


