package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ApartmentAttributeType generated by hbm2java
 */
@Entity
@Table (name = "apartment_attribute_type", catalog = "flexpay_db")
public class ApartmentAttributeType implements Serializable {

	// Fields

	private int id;
	private String attributeTypeCode;
	private Set<ApartmentAttributeTypeName> apartmentAttributeTypeNames = new HashSet<ApartmentAttributeTypeName>(0);
	private Set<ApartmentAttribute> apartmentAttributes = new HashSet<ApartmentAttribute>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public ApartmentAttributeType() {
	}

	/**
	 * minimal constructor
	 */
	public ApartmentAttributeType(int id, String attributeTypeCode) {
		this.id = id;
		this.attributeTypeCode = attributeTypeCode;
	}

	/**
	 * full constructor
	 */
	public ApartmentAttributeType(int id, String attributeTypeCode, Set<ApartmentAttributeTypeName> apartmentAttributeTypeNames, Set<ApartmentAttribute> apartmentAttributes) {
		this.id = id;
		this.attributeTypeCode = attributeTypeCode;
		this.apartmentAttributeTypeNames = apartmentAttributeTypeNames;
		this.apartmentAttributes = apartmentAttributes;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "attribute_type_code", unique = false, nullable = false, insertable = true, updatable = true)
	public String getAttributeTypeCode() {
		return this.attributeTypeCode;
	}

	public void setAttributeTypeCode(String attributeTypeCode) {
		this.attributeTypeCode = attributeTypeCode;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "apartmentAttributeType")
	public Set<ApartmentAttributeTypeName> getApartmentAttributeTypeNames() {
		return this.apartmentAttributeTypeNames;
	}

	public void setApartmentAttributeTypeNames(Set<ApartmentAttributeTypeName> apartmentAttributeTypeNames) {
		this.apartmentAttributeTypeNames = apartmentAttributeTypeNames;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "apartmentAttributeType")
	public Set<ApartmentAttribute> getApartmentAttributes() {
		return this.apartmentAttributes;
	}

	public void setApartmentAttributes(Set<ApartmentAttribute> apartmentAttributes) {
		this.apartmentAttributes = apartmentAttributes;
	}

}


