package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * ApartmentNumber generated by hbm2java
 */
@Entity
@Table (name = "apartment_number", catalog = "flexpay_db")
public class ApartmentNumber implements Serializable {

	// Fields

	private int id;
	private Apartment apartment;
	private Date begin;
	private Date end;
	private String value;

	// Constructors

	/**
	 * default constructor
	 */
	public ApartmentNumber() {
	}

	/**
	 * full constructor
	 */
	public ApartmentNumber(int id, Apartment apartment, Date begin, Date end, String value) {
		this.id = id;
		this.apartment = apartment;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Apartment_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Apartment getApartment() {
		return this.apartment;
	}

	public void setApartment(Apartment apartment) {
		this.apartment = apartment;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}


