package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * ApartmentAttributeTypeName generated by hbm2java
 */
@Entity
@Table (name = "apartment_attribute_type_name", catalog = "flexpay_db")
public class ApartmentAttributeTypeName implements Serializable {

	// Fields

	private int id;
	private ApartmentAttributeType apartmentAttributeType;
	private String name;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public ApartmentAttributeTypeName() {
	}

	/**
	 * full constructor
	 */
	public ApartmentAttributeTypeName(int id, ApartmentAttributeType apartmentAttributeType, String name, String lang) {
		this.id = id;
		this.apartmentAttributeType = apartmentAttributeType;
		this.name = name;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Apartment_Attribute_Type_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public ApartmentAttributeType getApartmentAttributeType() {
		return this.apartmentAttributeType;
	}

	public void setApartmentAttributeType(ApartmentAttributeType apartmentAttributeType) {
		this.apartmentAttributeType = apartmentAttributeType;
	}

	@Column (name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


