package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * BuildingAttribute generated by hbm2java
 */
@Entity
@Table (name = "building_attribute", catalog = "flexpay_db")
public class BuildingAttribute implements Serializable {

	// Fields

	private int id;
	private Buildings buildings;
	private BuildingAttributeType buildingAttributeType;
	private String value;

	// Constructors

	/**
	 * default constructor
	 */
	public BuildingAttribute() {
	}

	/**
	 * full constructor
	 */
	public BuildingAttribute(int id, Buildings buildings, BuildingAttributeType buildingAttributeType, String value) {
		this.id = id;
		this.buildings = buildings;
		this.buildingAttributeType = buildingAttributeType;
		this.value = value;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Buildings_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Buildings getBuildings() {
		return this.buildings;
	}

	public void setBuildings(Buildings buildings) {
		this.buildings = buildings;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "attribute_type_id", unique = false, nullable = false, insertable = true, updatable = true)
	public BuildingAttributeType getBuildingAttributeType() {
		return this.buildingAttributeType;
	}

	public void setBuildingAttributeType(BuildingAttributeType buildingAttributeType) {
		this.buildingAttributeType = buildingAttributeType;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}


