package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * BuildingAttributeType generated by hbm2java
 */
@Entity
@Table (name = "building_attribute_type", catalog = "flexpay_db")
public class BuildingAttributeType implements Serializable {

	// Fields

	private int id;
	private Set<BuildingAttribute> buildingAttributes = new HashSet<BuildingAttribute>(0);
	private Set<BuildingAttributeTypeLang> buildingAttributeTypeLangs = new HashSet<BuildingAttributeTypeLang>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public BuildingAttributeType() {
	}

	/**
	 * minimal constructor
	 */
	public BuildingAttributeType(int id) {
		this.id = id;
	}

	/**
	 * full constructor
	 */
	public BuildingAttributeType(int id, Set<BuildingAttribute> buildingAttributes, Set<BuildingAttributeTypeLang> buildingAttributeTypeLangs) {
		this.id = id;
		this.buildingAttributes = buildingAttributes;
		this.buildingAttributeTypeLangs = buildingAttributeTypeLangs;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "buildingAttributeType")
	public Set<BuildingAttribute> getBuildingAttributes() {
		return this.buildingAttributes;
	}

	public void setBuildingAttributes(Set<BuildingAttribute> buildingAttributes) {
		this.buildingAttributes = buildingAttributes;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "buildingAttributeType")
	public Set<BuildingAttributeTypeLang> getBuildingAttributeTypeLangs() {
		return this.buildingAttributeTypeLangs;
	}

	public void setBuildingAttributeTypeLangs(Set<BuildingAttributeTypeLang> buildingAttributeTypeLangs) {
		this.buildingAttributeTypeLangs = buildingAttributeTypeLangs;
	}

}


