package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * BuildingStatus generated by hbm2java
 */
@Entity
@Table (name = "building_status", catalog = "flexpay_db")
public class BuildingStatus implements Serializable {

	// Fields

	private int id;
	private Building building;
	private Date begin;
	private Date end;
	private int value;

	// Constructors

	/**
	 * default constructor
	 */
	public BuildingStatus() {
	}

	/**
	 * full constructor
	 */
	public BuildingStatus(int id, Building building, Date begin, Date end, int value) {
		this.id = id;
		this.building = building;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Building_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Building getBuilding() {
		return this.building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true)
	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

}


