package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingAttribute generated by hbm2java
 */
@Entity
@Table(name="building_attribute"
    ,catalog="flexpay_db"
)
public class BuildingAttribute  implements java.io.Serializable {


     private int id;
     private Buildings buildings;
     private BuildingAttributeType buildingAttributeType;
     private String value;

    public BuildingAttribute() {
    }

    public BuildingAttribute(int id, Buildings buildings, BuildingAttributeType buildingAttributeType, String value) {
       this.id = id;
       this.buildings = buildings;
       this.buildingAttributeType = buildingAttributeType;
       this.value = value;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Buildings_ID", nullable=false)
    public Buildings getBuildings() {
        return this.buildings;
    }
    
    public void setBuildings(Buildings buildings) {
        this.buildings = buildings;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attribute_type_id", nullable=false)
    public BuildingAttributeType getBuildingAttributeType() {
        return this.buildingAttributeType;
    }
    
    public void setBuildingAttributeType(BuildingAttributeType buildingAttributeType) {
        this.buildingAttributeType = buildingAttributeType;
    }
    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


