package org.flexpay.ab.persistence;

import org.flexpay.common.persistence.AttributeValueKey;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
@Entity
@Table (name = "country", catalog = "flexpay_db")
public class Country implements Serializable {

	// Fields
	private Long id;
    /**
             <map name="attributes" cascade="all-delete-orphan" table="country_names">
                <key column="countryID"/>
                <composite-map-key class="AttributeValueKey">
                    <key-property name="name"/>
                    <key-property name="lang" column="lang"/>
                </composite-map-key>
                <element type="string" column="shortName" length="255"/>
            </map>
     *
     */
    @ManyToOne (fetch = FetchType.LAZY)
    @JoinColumns(
            {@JoinColumn (name="name",referencedColumnName = "")
                    }
    )
    
    private Map<AttributeValueKey, String> countryNames = new HashMap<AttributeValueKey, String>();
//    private Map<String, LongShortValue> countryNames = new HashMap<String, LongShortValue>();
    private int countryStatus;
	private Set<Region> regions = new HashSet<Region>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public Country() {
	}

	/**
	 * Getter for property 'id'.
	 *
	 * @return Value for property 'id'.
	 */
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Long getId() {
		return this.id;
	}

	/**
	 * Setter for property 'id'.
	 *
	 * @param id Value to set for property 'id'.
	 */
	public void setId(Long id) {
		this.id = id;
	}


	/**
	 * Getter for property 'countryStatus'.
	 *
	 * @return Value for property 'countryStatus'.
	 */
	@Column (name = "Country_status", unique = false, nullable = false, insertable = true, updatable = true)
	public int getCountryStatus() {
		return this.countryStatus;
	}

	/**
	 * Setter for property 'countryStatus'.
	 *
	 * @param countryStatus Value to set for property 'countryStatus'.
	 */
	public void setCountryStatus(int countryStatus) {
		this.countryStatus = countryStatus;
	}

	/**
	 * Getter for property 'regions'.
	 *
	 * @return Value for property 'regions'.
	 */
	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Region> getRegions() {
		return this.regions;
	}

	/**
	 * Setter for property 'regions'.
	 *
	 * @param regions Value to set for property 'regions'.
	 */
	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

    public void addCountryName(String name, String lang, String shortName){
        if (name==null || name.length()==0 ||
                lang==null || lang.length()==0){
            throw new NullPointerException();
        }
        AttributeValueKey key = new AttributeValueKey(name,lang);
        countryNames.put(key,shortName);
    }

    public void deleteCountryName (String name,String lang){
        AttributeValueKey key = new AttributeValueKey(name,lang);
        countryNames.remove(key);
    }

    public String getCountryShortName (String name,String lang){
        AttributeValueKey key = new AttributeValueKey(name,lang);
        return getCountryShortName(key);
    }

    public String getCountryShortName (AttributeValueKey key){
        return countryNames.get(key);
    }

    public Set<AttributeValueKey> getCounntryNames(){
        return countryNames.keySet();
    }

    public Map<AttributeValueKey,String> getCountryNames(){
        return countryNames;
    }

    public void setCountryNames(Map<AttributeValueKey,String> values){
        this.countryNames = values;
    }
}
