package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
@Entity
@Table (name = "country", catalog = "flexpay_db")
public class Country implements Serializable {

	// Fields

	private int id;
	private String countryName;
	private int countryStatus;
	private String countryShortName;
	private Set<Region> regions = new HashSet<Region>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public Country() {
	}

	/**
	 * minimal constructor
	 */
	public Country(int id, String countryName, int countryStatus, String countryShortName) {
		this.id = id;
		this.countryName = countryName;
		this.countryStatus = countryStatus;
		this.countryShortName = countryShortName;
	}

	/**
	 * full constructor
	 */
	public Country(int id, String countryName, int countryStatus, String countryShortName, Set<Region> regions) {
		this.id = id;
		this.countryName = countryName;
		this.countryStatus = countryStatus;
		this.countryShortName = countryShortName;
		this.regions = regions;
	}

	/**
	 * Getter for property 'id'.
	 *
	 * @return Value for property 'id'.
	 */
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	/**
	 * Setter for property 'id'.
	 *
	 * @param id Value to set for property 'id'.
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Getter for property 'countryName'.
	 *
	 * @return Value for property 'countryName'.
	 */
	@Column (name = "Country_Name", unique = false, nullable = false, insertable = true, updatable = true, length = 200)
	public String getCountryName() {
		return this.countryName;
	}

	/**
	 * Setter for property 'countryName'.
	 *
	 * @param countryName Value to set for property 'countryName'.
	 */
	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	/**
	 * Getter for property 'countryStatus'.
	 *
	 * @return Value for property 'countryStatus'.
	 */
	@Column (name = "Country_status", unique = false, nullable = false, insertable = true, updatable = true)
	public int getCountryStatus() {
		return this.countryStatus;
	}

	/**
	 * Setter for property 'countryStatus'.
	 *
	 * @param countryStatus Value to set for property 'countryStatus'.
	 */
	public void setCountryStatus(int countryStatus) {
		this.countryStatus = countryStatus;
	}

	/**
	 * Getter for property 'countryShortName'.
	 *
	 * @return Value for property 'countryShortName'.
	 */
	@Column (name = "Country_Short_Name", unique = false, nullable = false, insertable = true, updatable = true, length = 200)
	public String getCountryShortName() {
		return this.countryShortName;
	}

	/**
	 * Setter for property 'countryShortName'.
	 *
	 * @param countryShortName Value to set for property 'countryShortName'.
	 */
	public void setCountryShortName(String countryShortName) {
		this.countryShortName = countryShortName;
	}

	/**
	 * Getter for property 'regions'.
	 *
	 * @return Value for property 'regions'.
	 */
	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Region> getRegions() {
		return this.regions;
	}

	/**
	 * Setter for property 'regions'.
	 *
	 * @param regions Value to set for property 'regions'.
	 */
	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

}


