package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * DistrictNameLangValue generated by hbm2java
 */
@Entity
@Table (name = "district_name_lang_value", catalog = "flexpay_db")
public class DistrictNameLangValue implements Serializable {

	// Fields

	private int id;
	private DistrictName districtName;
	private String value;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public DistrictNameLangValue() {
	}

	/**
	 * full constructor
	 */
	public DistrictNameLangValue(int id, DistrictName districtName, String value, String lang) {
		this.id = id;
		this.districtName = districtName;
		this.value = value;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "DistrictName_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public DistrictName getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(DistrictName districtName) {
		this.districtName = districtName;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


