package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * District generated by hbm2java
 */
@Entity
@Table (name = "district", catalog = "flexpay_db")
public class District implements Serializable {

	// Fields

	private int id;
	private Town town;
	private int districtStatus;
	private Set<Street> streets = new HashSet<Street>(0);
	private Set<DistrictName> districtNames = new HashSet<DistrictName>(0);
	private Set<Building> buildings = new HashSet<Building>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public District() {
	}

	/**
	 * minimal constructor
	 */
	public District(int id, Town town, int districtStatus) {
		this.id = id;
		this.town = town;
		this.districtStatus = districtStatus;
	}

	/**
	 * full constructor
	 */
	public District(int id, Town town, int districtStatus, Set<Street> streets, Set<DistrictName> districtNames, Set<Building> buildings) {
		this.id = id;
		this.town = town;
		this.districtStatus = districtStatus;
		this.streets = streets;
		this.districtNames = districtNames;
		this.buildings = buildings;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Town_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Town getTown() {
		return this.town;
	}

	public void setTown(Town town) {
		this.town = town;
	}

	@Column (name = "District_Status", unique = false, nullable = false, insertable = true, updatable = true)
	public int getDistrictStatus() {
		return this.districtStatus;
	}

	public void setDistrictStatus(int districtStatus) {
		this.districtStatus = districtStatus;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Street> getStreets() {
		return this.streets;
	}

	public void setStreets(Set<Street> streets) {
		this.streets = streets;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "district")
	public Set<DistrictName> getDistrictNames() {
		return this.districtNames;
	}

	public void setDistrictNames(Set<DistrictName> districtNames) {
		this.districtNames = districtNames;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Building> getBuildings() {
		return this.buildings;
	}

	public void setBuildings(Set<Building> buildings) {
		this.buildings = buildings;
	}

}


