package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * History generated by hbm2java
 */
@Entity
@Table (name = "history", catalog = "flexpay_db")
public class History implements Serializable {

	// Fields

	private int id;
	private History history;
	private Date recordDate;
	private String actionType;
	private String value;
	private String oldValue;
	private Set<History> histories = new HashSet<History>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public History() {
	}

	/**
	 * minimal constructor
	 */
	public History(int id, Date recordDate, String actionType, String value) {
		this.id = id;
		this.recordDate = recordDate;
		this.actionType = actionType;
		this.value = value;
	}

	/**
	 * full constructor
	 */
	public History(int id, History history, Date recordDate, String actionType, String value, String oldValue, Set<History> histories) {
		this.id = id;
		this.history = history;
		this.recordDate = recordDate;
		this.actionType = actionType;
		this.value = value;
		this.oldValue = oldValue;
		this.histories = histories;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "History_ID", unique = false, nullable = true, insertable = true, updatable = true)
	public History getHistory() {
		return this.history;
	}

	public void setHistory(History history) {
		this.history = history;
	}

	@Column (name = "record_date", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Column (name = "action_type", unique = false, nullable = false, insertable = true, updatable = true)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true, length = 4000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column (name = "old_value", unique = false, nullable = true, insertable = true, updatable = true, length = 4000)
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "history")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

}


