package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * IdentityName generated by hbm2java
 */
@Entity
@Table (name = "identity_name", catalog = "flexpay_db")
public class IdentityName implements Serializable {

	// Fields

	private int id;
	private IdentityType identityType;
	private String name;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public IdentityName() {
	}

	/**
	 * full constructor
	 */
	public IdentityName(int id, IdentityType identityType, String name, String lang) {
		this.id = id;
		this.identityType = identityType;
		this.name = name;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "IdentityType_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public IdentityType getIdentityType() {
		return this.identityType;
	}

	public void setIdentityType(IdentityType identityType) {
		this.identityType = identityType;
	}

	@Column (name = "Name", unique = false, nullable = false, insertable = true, updatable = true, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true, length = 120)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


