package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IdentityName generated by hbm2java
 */
@Entity
@Table(name="identity_name"
    ,catalog="flexpay_db"
)
public class IdentityName  implements java.io.Serializable {


     private int id;
     private IdentityType identityType;
     private String name;
     private String lang;

    public IdentityName() {
    }

    public IdentityName(int id, IdentityType identityType, String name, String lang) {
       this.id = id;
       this.identityType = identityType;
       this.name = name;
       this.lang = lang;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdentityType_ID", nullable=false)
    public IdentityType getIdentityType() {
        return this.identityType;
    }
    
    public void setIdentityType(IdentityType identityType) {
        this.identityType = identityType;
    }
    
    @Column(name="Name", nullable=false, length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="LANG", nullable=false, length=120)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }




}


