package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * IdentityType generated by hbm2java
 */
@Entity
@Table (name = "identity_type", catalog = "flexpay_db")
public class IdentityType implements Serializable {

	// Fields

	private int id;
	private Set<IdentityName> identityNames = new HashSet<IdentityName>(0);
	private Set<PersonIdentity> personIdentities = new HashSet<PersonIdentity>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public IdentityType() {
	}

	/**
	 * minimal constructor
	 */
	public IdentityType(int id) {
		this.id = id;
	}

	/**
	 * full constructor
	 */
	public IdentityType(int id, Set<IdentityName> identityNames, Set<PersonIdentity> personIdentities) {
		this.id = id;
		this.identityNames = identityNames;
		this.personIdentities = personIdentities;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "identityType")
	public Set<IdentityName> getIdentityNames() {
		return this.identityNames;
	}

	public void setIdentityNames(Set<IdentityName> identityNames) {
		this.identityNames = identityNames;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "identityType")
	public Set<PersonIdentity> getPersonIdentities() {
		return this.personIdentities;
	}

	public void setPersonIdentities(Set<PersonIdentity> personIdentities) {
		this.personIdentities = personIdentities;
	}

}


