package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Identities generated by hbm2java
 */
@Entity
@Table (name = "identities", catalog = "flexpay_db")
public class Identities implements Serializable {

	// Fields

	private int id;
	private PersonIdentity personIdentity;
	private Person person;
	private int status;

	// Constructors

	/**
	 * default constructor
	 */
	public Identities() {
	}

	/**
	 * full constructor
	 */
	public Identities(int id, PersonIdentity personIdentity, Person person, int status) {
		this.id = id;
		this.personIdentity = personIdentity;
		this.person = person;
		this.status = status;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Idenity_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public PersonIdentity getPersonIdentity() {
		return this.personIdentity;
	}

	public void setPersonIdentity(PersonIdentity personIdentity) {
		this.personIdentity = personIdentity;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Person_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column (name = "status", unique = false, nullable = false, insertable = true, updatable = true)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}


