package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdentityType generated by hbm2java
 */
@Entity
@Table(name="identity_type"
    ,catalog="flexpay_db"
)
public class IdentityType  implements java.io.Serializable {


     private int id;
     private Set<IdentityName> identityNames = new HashSet<IdentityName>(0);
     private Set<PersonIdentity> personIdentities = new HashSet<PersonIdentity>(0);

    public IdentityType() {
    }

	
    public IdentityType(int id) {
        this.id = id;
    }
    public IdentityType(int id, Set<IdentityName> identityNames, Set<PersonIdentity> personIdentities) {
       this.id = id;
       this.identityNames = identityNames;
       this.personIdentities = personIdentities;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="identityType")
    public Set<IdentityName> getIdentityNames() {
        return this.identityNames;
    }
    
    public void setIdentityNames(Set<IdentityName> identityNames) {
        this.identityNames = identityNames;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="identityType")
    public Set<PersonIdentity> getPersonIdentities() {
        return this.personIdentities;
    }
    
    public void setPersonIdentities(Set<PersonIdentity> personIdentities) {
        this.personIdentities = personIdentities;
    }




}


