package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import org.flexpay.ab.persistence.temp.Person;
import org.flexpay.ab.persistence.temp.PersonIdentity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Identities generated by hbm2java
 */
@Entity
@Table(name="identities"
    ,catalog="flexpay_db"
)
public class Identities  implements java.io.Serializable {


     private int id;
     private PersonIdentity personIdentity;
     private Person person;
     private int status;

    public Identities() {
    }

    public Identities(int id, PersonIdentity personIdentity, Person person, int status) {
       this.id = id;
       this.personIdentity = personIdentity;
       this.person = person;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Idenity_ID", nullable=false)
    public PersonIdentity getPersonIdentity() {
        return this.personIdentity;
    }
    
    public void setPersonIdentity(PersonIdentity personIdentity) {
        this.personIdentity = personIdentity;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Person_ID", nullable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


