package org.flexpay.ab.persistence;

import org.flexpay.common.persistence.AttributeTranslation;

/**
 * PersonIdentityAttribute generated by hbm2java
 */
public class PersonIdentityAttribute extends AttributeTranslation {

	public PersonIdentityAttribute() {
	}
}
