package org.flexpay.ab.persistence;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;

/**
 * PersonactId generated by hbm2java
 */
@Embeddable
public class PersonactId implements Serializable {

	// Fields

	private int id;
	private int actId;
	private int personId;

	// Constructors

	/**
	 * default constructor
	 */
	public PersonactId() {
	}

	/**
	 * full constructor
	 */
	public PersonactId(int id, int actId, int personId) {
		this.id = id;
		this.actId = actId;
		this.personId = personId;
	}

	// Property accessors

	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "Act_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getActId() {
		return this.actId;
	}

	public void setActId(int actId) {
		this.actId = actId;
	}

	@Column (name = "Person_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

}


