package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Personact generated by hbm2java
 */
@Entity
@Table (name = "personact", catalog = "flexpay_db")
public class Personact implements Serializable {

	// Fields

	private PersonactId id;
	private Person person;
	private Act act;

	// Constructors

	/**
	 * default constructor
	 */
	public Personact() {
	}

	/**
	 * full constructor
	 */
	public Personact(PersonactId id, Person person, Act act) {
		this.id = id;
		this.person = person;
		this.act = act;
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides ({@AttributeOverride (name = "id", column = @Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)), @AttributeOverride (name = "actId", column = @Column (name = "Act_ID", unique = false, nullable = false, insertable = true, updatable = true)), @AttributeOverride (name = "personId", column = @Column (name = "Person_ID", unique = false, nullable = false, insertable = true, updatable = true))})
	public PersonactId getId() {
		return this.id;
	}

	public void setId(PersonactId id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Person_ID", unique = false, nullable = false, insertable = false, updatable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Act_ID", unique = false, nullable = false, insertable = false, updatable = false)
	public Act getAct() {
		return this.act;
	}

	public void setAct(Act act) {
		this.act = act;
	}

}


