package org.flexpay.ab.persistence;

import org.flexpay.common.persistence.DomainObject;

import java.util.Collections;
import java.util.Date;
import java.util.Set;

/**
 * PersonIdentity generated by hbm2java
 */
public class PersonIdentity extends DomainObject {

	private IdentityType identityType;
	private Person person;
	private Date beginDate;
	private Date endDate;
	private Date birthDate;
	private String organization;
	private String firstName;
	private String lastName;
	private String middleName;
	private int serialNumber;
	private int documentNumber;
	private boolean isDefault;
	private Set<PersonIdentityAttribute> personIdentityAttributes = Collections.emptySet();

	public PersonIdentity() {
	}

	public IdentityType getIdentityType() {
		return this.identityType;
	}

	public void setIdentityType(IdentityType identityType) {
		this.identityType = identityType;
	}

	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public int getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(int serialNumber) {
		this.serialNumber = serialNumber;
	}

	public int getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(int documentNumber) {
		this.documentNumber = documentNumber;
	}

	public Set<PersonIdentityAttribute> getPersonIdentityAttributes() {
		return this.personIdentityAttributes;
	}

	public void setPersonIdentityAttributes(Set<PersonIdentityAttribute> personIdentityAttributes) {
		this.personIdentityAttributes = personIdentityAttributes;
	}

	/**
	 * Getter for property 'birthDate'.
	 *
	 * @return Value for property 'birthDate'.
	 */
	public Date getBirthDate() {
		return birthDate;
	}

	/**
	 * Setter for property 'birthDate'.
	 *
	 * @param birthDate Value to set for property 'birthDate'.
	 */
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * Getter for property 'person'.
	 *
	 * @return Value for property 'person'.
	 */
	public Person getPerson() {
		return person;
	}

	/**
	 * Setter for property 'person'.
	 *
	 * @param person Value to set for property 'person'.
	 */
	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * Getter for property 'default'.
	 *
	 * @return Value for property 'default'.
	 */
	public boolean isDefault() {
		return isDefault;
	}

	/**
	 * Setter for property 'default'.
	 *
	 * @param isDefault Value to set for property 'default'.
	 */
	public void setDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}
}
