package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RegionNameLangValue generated by hbm2java
 */
@Entity
@Table(name="region_name_lang_value"
    ,catalog="flexpay_db"
)
public class RegionNameLangValue  implements java.io.Serializable {


     private int id;
     private RegionName regionName;
     private String value;
     private String lang;

    public RegionNameLangValue() {
    }

    public RegionNameLangValue(int id, RegionName regionName, String value, String lang) {
       this.id = id;
       this.regionName = regionName;
       this.value = value;
       this.lang = lang;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RegionName_ID", nullable=false)
    public RegionName getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(RegionName regionName) {
        this.regionName = regionName;
    }
    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="LANG", nullable=false)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }




}


