package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * RegionNameLangValue generated by hbm2java
 */
@Entity
@Table (name = "region_name_lang_value", catalog = "flexpay_db")
public class RegionNameLangValue implements Serializable {

	// Fields

	private int id;
	private RegionName regionName;
	private String value;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public RegionNameLangValue() {
	}

	/**
	 * full constructor
	 */
	public RegionNameLangValue(int id, RegionName regionName, String value, String lang) {
		this.id = id;
		this.regionName = regionName;
		this.value = value;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "RegionName_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public RegionName getRegionName() {
		return this.regionName;
	}

	public void setRegionName(RegionName regionName) {
		this.regionName = regionName;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


