package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import org.flexpay.common.persistence.LongShortValue;
import org.flexpay.common.persistence.LangNameObject;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region"
    ,catalog="flexpay_db"
)
public class Region  extends LangNameObject implements java.io.Serializable  {


     private int id;
     private Country country;
     private int regionStatus;
     private Set<Town> towns = new HashSet<Town>(0);

    public Region() {
    }

	
    public Region(Country country, int regionStatus, String regionShortName) {
        this.country = country;
        this.regionStatus = regionStatus;
    }

    @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Country_ID", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    
    @Column(name="Region_Status", nullable=false)
    public int getRegionStatus() {
        return this.regionStatus;
    }
    
    public void setRegionStatus(int regionStatus) {
        this.regionStatus = regionStatus;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<Town> getTowns() {
        return this.towns;
    }
    
    public void setTowns(Set<Town> towns) {
        this.towns = towns;
    }




}


