package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RegionName generated by hbm2java
 */
@Entity
@Table (name = "region_name", catalog = "flexpay_db")
public class RegionName implements Serializable {

	// Fields

	private int id;
	private Region region;
	private Date begin;
	private Date end;
	private Set<RegionNameLangValue> regionNameLangValues = new HashSet<RegionNameLangValue>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public RegionName() {
	}

	/**
	 * minimal constructor
	 */
	public RegionName(int id, Region region, Date begin, Date end) {
		this.id = id;
		this.region = region;
		this.begin = begin;
		this.end = end;
	}

	/**
	 * full constructor
	 */
	public RegionName(int id, Region region, Date begin, Date end, Set<RegionNameLangValue> regionNameLangValues) {
		this.id = id;
		this.region = region;
		this.begin = begin;
		this.end = end;
		this.regionNameLangValues = regionNameLangValues;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Region_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "regionName")
	public Set<RegionNameLangValue> getRegionNameLangValues() {
		return this.regionNameLangValues;
	}

	public void setRegionNameLangValues(Set<RegionNameLangValue> regionNameLangValues) {
		this.regionNameLangValues = regionNameLangValues;
	}

}


