package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region"
    ,catalog="flexpay_db"
)
public class Region  implements java.io.Serializable {


     private int id;
     private Country country;
     private int regionStatus;
     private String regionShortName;
     private Set<RegionName> regionNames = new HashSet<RegionName>(0);
     private Set<Town> towns = new HashSet<Town>(0);

    public Region() {
    }

	
    public Region(int id, Country country, int regionStatus, String regionShortName) {
        this.id = id;
        this.country = country;
        this.regionStatus = regionStatus;
        this.regionShortName = regionShortName;
    }
    public Region(int id, Country country, int regionStatus, String regionShortName, Set<RegionName> regionNames, Set<Town> towns) {
       this.id = id;
       this.country = country;
       this.regionStatus = regionStatus;
       this.regionShortName = regionShortName;
       this.regionNames = regionNames;
       this.towns = towns;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Country_ID", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    
    @Column(name="Region_Status", nullable=false)
    public int getRegionStatus() {
        return this.regionStatus;
    }
    
    public void setRegionStatus(int regionStatus) {
        this.regionStatus = regionStatus;
    }
    
    @Column(name="Region_Short_Name", nullable=false, length=200)
    public String getRegionShortName() {
        return this.regionShortName;
    }
    
    public void setRegionShortName(String regionShortName) {
        this.regionShortName = regionShortName;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<RegionName> getRegionNames() {
        return this.regionNames;
    }
    
    public void setRegionNames(Set<RegionName> regionNames) {
        this.regionNames = regionNames;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<Town> getTowns() {
        return this.towns;
    }
    
    public void setTowns(Set<Town> towns) {
        this.towns = towns;
    }




}


