package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * RoomAttribute generated by hbm2java
 */
@Entity
@Table (name = "room_attribute", catalog = "flexpay_db")
public class RoomAttribute implements Serializable {

	// Fields

	private int id;
	private Room room;
	private RoomAttributeType roomAttributeType;
	private Date begin;
	private Date end;
	private String value;

	// Constructors

	/**
	 * default constructor
	 */
	public RoomAttribute() {
	}

	/**
	 * minimal constructor
	 */
	public RoomAttribute(int id, Date begin, Date end, String value) {
		this.id = id;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	/**
	 * full constructor
	 */
	public RoomAttribute(int id, Room room, RoomAttributeType roomAttributeType, Date begin, Date end, String value) {
		this.id = id;
		this.room = room;
		this.roomAttributeType = roomAttributeType;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Room_ID", unique = false, nullable = true, insertable = true, updatable = true)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Room_Attribute_type_ID", unique = false, nullable = true, insertable = true, updatable = true)
	public RoomAttributeType getRoomAttributeType() {
		return this.roomAttributeType;
	}

	public void setRoomAttributeType(RoomAttributeType roomAttributeType) {
		this.roomAttributeType = roomAttributeType;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true, length = 2000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}


