package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * RoomAttributeTypeName generated by hbm2java
 */
@Entity
@Table (name = "room_attribute_type_name", catalog = "flexpay_db")
public class RoomAttributeTypeName implements Serializable {

	// Fields

	private int id;
	private RoomAttributeType roomAttributeType;
	private String name;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public RoomAttributeTypeName() {
	}

	/**
	 * full constructor
	 */
	public RoomAttributeTypeName(int id, RoomAttributeType roomAttributeType, String name, String lang) {
		this.id = id;
		this.roomAttributeType = roomAttributeType;
		this.name = name;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Room_Attribute_Type_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public RoomAttributeType getRoomAttributeType() {
		return this.roomAttributeType;
	}

	public void setRoomAttributeType(RoomAttributeType roomAttributeType) {
		this.roomAttributeType = roomAttributeType;
	}

	@Column (name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


