package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * RoomAttributeType generated by hbm2java
 */
@Entity
@Table (name = "room_attribute_type", catalog = "flexpay_db")
public class RoomAttributeType implements Serializable {

	// Fields

	private int id;
	private String attributeTypeCode;
	private Set<RoomAttributeTypeName> roomAttributeTypeNames = new HashSet<RoomAttributeTypeName>(0);
	private Set<RoomAttribute> roomAttributes = new HashSet<RoomAttribute>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public RoomAttributeType() {
	}

	/**
	 * minimal constructor
	 */
	public RoomAttributeType(int id, String attributeTypeCode) {
		this.id = id;
		this.attributeTypeCode = attributeTypeCode;
	}

	/**
	 * full constructor
	 */
	public RoomAttributeType(int id, String attributeTypeCode, Set<RoomAttributeTypeName> roomAttributeTypeNames, Set<RoomAttribute> roomAttributes) {
		this.id = id;
		this.attributeTypeCode = attributeTypeCode;
		this.roomAttributeTypeNames = roomAttributeTypeNames;
		this.roomAttributes = roomAttributes;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column (name = "attribute_Type_code", unique = false, nullable = false, insertable = true, updatable = true)
	public String getAttributeTypeCode() {
		return this.attributeTypeCode;
	}

	public void setAttributeTypeCode(String attributeTypeCode) {
		this.attributeTypeCode = attributeTypeCode;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "roomAttributeType")
	public Set<RoomAttributeTypeName> getRoomAttributeTypeNames() {
		return this.roomAttributeTypeNames;
	}

	public void setRoomAttributeTypeNames(Set<RoomAttributeTypeName> roomAttributeTypeNames) {
		this.roomAttributeTypeNames = roomAttributeTypeNames;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "roomAttributeType")
	public Set<RoomAttribute> getRoomAttributes() {
		return this.roomAttributes;
	}

	public void setRoomAttributes(Set<RoomAttribute> roomAttributes) {
		this.roomAttributes = roomAttributes;
	}

}


