package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import org.flexpay.ab.persistence.temp.Buildings;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Street generated by hbm2java
 */
@Entity
@Table (name = "street"
		, catalog = "flexpay_db"
)
public class Street implements java.io.Serializable {


	private int id;
	private District district;
	private Town town;
	private StreetType streetType;
	private int streetStatus;
	private Set<StreetName> streetNames = new HashSet<StreetName>(0);
	private Set<Buildings> buildingses = new HashSet<Buildings>(0);

	public Street() {
	}


	public Street(int id, Town town, StreetType streetType, int streetStatus) {
		this.id = id;
		this.town = town;
		this.streetType = streetType;
		this.streetStatus = streetStatus;
	}

	public Street(int id, District district, Town town, StreetType streetType, int streetStatus, Set<StreetName> streetNames, Set<Buildings> buildingses) {
		this.id = id;
		this.district = district;
		this.town = town;
		this.streetType = streetType;
		this.streetStatus = streetStatus;
		this.streetNames = streetNames;
		this.buildingses = buildingses;
	}

	@Id

	@Column (name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "District_ID")
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Town_ID", nullable = false)
	public Town getTown() {
		return this.town;
	}

	public void setTown(Town town) {
		this.town = town;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Street_Type_ID", nullable = false)
	public StreetType getStreetType() {
		return this.streetType;
	}

	public void setStreetType(StreetType streetType) {
		this.streetType = streetType;
	}

	@Column (name = "Street_status", nullable = false)
	public int getStreetStatus() {
		return this.streetStatus;
	}

	public void setStreetStatus(int streetStatus) {
		this.streetStatus = streetStatus;
	}

	@OneToMany (fetch = FetchType.LAZY, mappedBy = "street")
	public Set<StreetName> getStreetNames() {
		return this.streetNames;
	}

	public void setStreetNames(Set<StreetName> streetNames) {
		this.streetNames = streetNames;
	}

	@OneToMany (fetch = FetchType.LAZY, mappedBy = "street")
	public Set<Buildings> getBuildingses() {
		return this.buildingses;
	}

	public void setBuildingses(Set<Buildings> buildingses) {
		this.buildingses = buildingses;
	}

}


