package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StreetType generated by hbm2java
 */
@Entity
@Table (name = "street_type", catalog = "flexpay_db")
public class StreetType implements Serializable {

	// Fields

	private int id;
	private StreetTypes streetTypes;
	private Date begin;
	private Date end;
	private int streetId;
	private Set<Street> streets = new HashSet<Street>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public StreetType() {
	}

	/**
	 * minimal constructor
	 */
	public StreetType(int id, Date begin, Date end, int streetId) {
		this.id = id;
		this.begin = begin;
		this.end = end;
		this.streetId = streetId;
	}

	/**
	 * full constructor
	 */
	public StreetType(int id, StreetTypes streetTypes, Date begin, Date end, int streetId, Set<Street> streets) {
		this.id = id;
		this.streetTypes = streetTypes;
		this.begin = begin;
		this.end = end;
		this.streetId = streetId;
		this.streets = streets;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Street_Type_ID", unique = false, nullable = true, insertable = true, updatable = true)
	public StreetTypes getStreetTypes() {
		return this.streetTypes;
	}

	public void setStreetTypes(StreetTypes streetTypes) {
		this.streetTypes = streetTypes;
	}

	@Column (name = "begin", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", unique = false, nullable = false, insertable = true, updatable = true, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column (name = "Street_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getStreetId() {
		return this.streetId;
	}

	public void setStreetId(int streetId) {
		this.streetId = streetId;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "streetType")
	public Set<Street> getStreets() {
		return this.streets;
	}

	public void setStreets(Set<Street> streets) {
		this.streets = streets;
	}

}


