package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StreetType generated by hbm2java
 */
@Entity
@Table(name="street_type"
    ,catalog="flexpay_db"
)
public class StreetType  implements java.io.Serializable {


     private int id;
     private StreetTypes streetTypes;
     private Date begin;
     private Date end;
     private int streetId;
     private Set<Street> streets = new HashSet<Street>(0);

    public StreetType() {
    }

	
    public StreetType(int id, Date begin, Date end, int streetId) {
        this.id = id;
        this.begin = begin;
        this.end = end;
        this.streetId = streetId;
    }
    public StreetType(int id, StreetTypes streetTypes, Date begin, Date end, int streetId, Set<Street> streets) {
       this.id = id;
       this.streetTypes = streetTypes;
       this.begin = begin;
       this.end = end;
       this.streetId = streetId;
       this.streets = streets;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Street_Type_ID")
    public StreetTypes getStreetTypes() {
        return this.streetTypes;
    }
    
    public void setStreetTypes(StreetTypes streetTypes) {
        this.streetTypes = streetTypes;
    }
    
    @Column(name="begin", nullable=false, length=0)
    public Date getBegin() {
        return this.begin;
    }
    
    public void setBegin(Date begin) {
        this.begin = begin;
    }
    
    @Column(name="end", nullable=false, length=0)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    
    @Column(name="Street_ID", nullable=false)
    public int getStreetId() {
        return this.streetId;
    }
    
    public void setStreetId(int streetId) {
        this.streetId = streetId;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="streetType")
    public Set<Street> getStreets() {
        return this.streets;
    }
    
    public void setStreets(Set<Street> streets) {
        this.streets = streets;
    }




}


