package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StreetTypes generated by hbm2java
 */
@Entity
@Table(name="street_types"
    ,catalog="flexpay_db"
)
public class StreetTypes  implements java.io.Serializable {


     private int id;
     private String name;
     private String lang;
     private Set<StreetType> streetTypes = new HashSet<StreetType>(0);

    public StreetTypes() {
    }

	
    public StreetTypes(int id, String name, String lang) {
        this.id = id;
        this.name = name;
        this.lang = lang;
    }
    public StreetTypes(int id, String name, String lang, Set<StreetType> streetTypes) {
       this.id = id;
       this.name = name;
       this.lang = lang;
       this.streetTypes = streetTypes;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Name", nullable=false, length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="LANG", nullable=false)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="streetTypes")
    public Set<StreetType> getStreetTypes() {
        return this.streetTypes;
    }
    
    public void setStreetTypes(Set<StreetType> streetTypes) {
        this.streetTypes = streetTypes;
    }




}


