package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StreetName generated by hbm2java
 */
@Entity
@Table(name="street_name"
    ,catalog="flexpay_db"
)
public class StreetName  implements java.io.Serializable {


     private int id;
     private Street street;
     private Date begin;
     private Date end;
     private Set<StreetNameLangValue> streetNameLangValues = new HashSet<StreetNameLangValue>(0);

    public StreetName() {
    }

	
    public StreetName(int id, Street street, Date begin, Date end) {
        this.id = id;
        this.street = street;
        this.begin = begin;
        this.end = end;
    }
    public StreetName(int id, Street street, Date begin, Date end, Set<StreetNameLangValue> streetNameLangValues) {
       this.id = id;
       this.street = street;
       this.begin = begin;
       this.end = end;
       this.streetNameLangValues = streetNameLangValues;
    }
   
     @Id 
    
    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Street_ID", nullable=false)
    public Street getStreet() {
        return this.street;
    }
    
    public void setStreet(Street street) {
        this.street = street;
    }
    
    @Column(name="begin", nullable=false, length=0)
    public Date getBegin() {
        return this.begin;
    }
    
    public void setBegin(Date begin) {
        this.begin = begin;
    }
    
    @Column(name="end", nullable=false, length=0)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="streetName")
    public Set<StreetNameLangValue> getStreetNameLangValues() {
        return this.streetNameLangValues;
    }
    
    public void setStreetNameLangValues(Set<StreetNameLangValue> streetNameLangValues) {
        this.streetNameLangValues = streetNameLangValues;
    }




}


