package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StreetNameLangValue generated by hbm2java
 */
@Entity
@Table(name="street_name_lang_value"
    ,catalog="flexpay_db"
)
public class StreetNameLangValue  implements java.io.Serializable {


     private int id;
     private StreetName streetName;
     private String value;
     private String lang;

    public StreetNameLangValue() {
    }

    public StreetNameLangValue(int id, StreetName streetName, String value, String lang) {
       this.id = id;
       this.streetName = streetName;
       this.value = value;
       this.lang = lang;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StreetName_ID", nullable=false)
    public StreetName getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(StreetName streetName) {
        this.streetName = streetName;
    }
    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Column(name="LANG", nullable=false)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }




}


