package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;

/**
 * StreetNameLangValue generated by hbm2java
 */
@Entity
@Table (name = "street_name_lang_value", catalog = "flexpay_db")
public class StreetNameLangValue implements Serializable {

	// Fields

	private int id;
	private StreetName streetName;
	private String value;
	private String lang;

	// Constructors

	/**
	 * default constructor
	 */
	public StreetNameLangValue() {
	}

	/**
	 * full constructor
	 */
	public StreetNameLangValue(int id, StreetName streetName, String value, String lang) {
		this.id = id;
		this.streetName = streetName;
		this.value = value;
		this.lang = lang;
	}

	// Property accessors
	@Id
	@Column (name = "id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "StreetName_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public StreetName getStreetName() {
		return this.streetName;
	}

	public void setStreetName(StreetName streetName) {
		this.streetName = streetName;
	}

	@Column (name = "value", unique = false, nullable = false, insertable = true, updatable = true)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column (name = "LANG", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


