package org.flexpay.ab.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TownTypes generated by hbm2java
 */
@Entity
@Table(name="town_types"
    ,catalog="flexpay_db"
)
public class TownTypes  implements java.io.Serializable {


     private int id;
     private String name;
     private String lang;
     private Set<TownType> townTypes = new HashSet<TownType>(0);

    public TownTypes() {
    }

	
    public TownTypes(int id, String name, String lang) {
        this.id = id;
        this.name = name;
        this.lang = lang;
    }
    public TownTypes(int id, String name, String lang, Set<TownType> townTypes) {
       this.id = id;
       this.name = name;
       this.lang = lang;
       this.townTypes = townTypes;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="Name", nullable=false, length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="LANG", nullable=false)
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="townTypes")
    public Set<TownType> getTownTypes() {
        return this.townTypes;
    }
    
    public void setTownTypes(Set<TownType> townTypes) {
        this.townTypes = townTypes;
    }




}


