package org.flexpay.ab.persistence;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Town generated by hbm2java
 */
@Entity
@Table (name = "town", catalog = "flexpay_db")
public class Town implements Serializable {

	// Fields

	private int id;
	private TownType townType;
	private Region region;
	private int townStatus;
	private Set<TownName> townNames = new HashSet<TownName>(0);
	private Set<District> districts = new HashSet<District>(0);
	private Set<Street> streets = new HashSet<Street>(0);

	// Constructors

	/**
	 * default constructor
	 */
	public Town() {
	}

	/**
	 * minimal constructor
	 */
	public Town(int id, Region region, int townStatus) {
		this.id = id;
		this.region = region;
		this.townStatus = townStatus;
	}

	/**
	 * full constructor
	 */
	public Town(int id, TownType townType, Region region, int townStatus, Set<TownName> townNames, Set<District> districts, Set<Street> streets) {
		this.id = id;
		this.townType = townType;
		this.region = region;
		this.townStatus = townStatus;
		this.townNames = townNames;
		this.districts = districts;
		this.streets = streets;
	}

	// Property accessors
	@Id
	@Column (name = "ID", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Town_Type_id", unique = false, nullable = true, insertable = true, updatable = true)
	public TownType getTownType() {
		return this.townType;
	}

	public void setTownType(TownType townType) {
		this.townType = townType;
	}

	@ManyToOne (cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn (name = "Region_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column (name = "Town_Status", unique = false, nullable = false, insertable = true, updatable = true)
	public int getTownStatus() {
		return this.townStatus;
	}

	public void setTownStatus(int townStatus) {
		this.townStatus = townStatus;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "town")
	public Set<TownName> getTownNames() {
		return this.townNames;
	}

	public void setTownNames(Set<TownName> townNames) {
		this.townNames = townNames;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "town")
	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

	@OneToMany (cascade = {}, fetch = FetchType.LAZY, mappedBy = "town")
	public Set<Street> getStreets() {
		return this.streets;
	}

	public void setStreets(Set<Street> streets) {
		this.streets = streets;
	}

}


