package org.flexpay.bti.persistence;

import java.io.Serializable;

/**
 * ActsId generated by hbm2java
 */
public class ActsId implements Serializable {

	// Fields

	private int apartmentRelationId;
	private int actId;

	// Constructors

	/**
	 * default constructor
	 */
	public ActsId() {
	}

	/**
	 * full constructor
	 */
	public ActsId(int apartmentRelationId, int actId) {
		this.apartmentRelationId = apartmentRelationId;
		this.actId = actId;
	}

	// Property accessors

	public int getApartmentRelationId() {
		return this.apartmentRelationId;
	}

	public void setApartmentRelationId(int apartmentRelationId) {
		this.apartmentRelationId = apartmentRelationId;
	}

	public int getActId() {
		return this.actId;
	}

	public void setActId(int actId) {
		this.actId = actId;
	}

}


