package org.flexpay.bti.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.*;

/**
 * RoomAttributeTypeName generated by hbm2java
 */
/*
@Entity
@Table (name = "room_attribute_type_name"
		, catalog = "flexpay_db"
)
*/
public class RoomAttributeTypeName implements java.io.Serializable {


	private int id;
	private RoomAttributeType roomAttributeType;
	private String name;
	private String lang;

	public RoomAttributeTypeName() {
	}

	public RoomAttributeTypeName(int id, RoomAttributeType roomAttributeType, String name, String lang) {
		this.id = id;
		this.roomAttributeType = roomAttributeType;
		this.name = name;
		this.lang = lang;
	}

	@Id

	@Column (name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Room_Attribute_Type_ID", nullable = false)
	public RoomAttributeType getRoomAttributeType() {
		return this.roomAttributeType;
	}

	public void setRoomAttributeType(RoomAttributeType roomAttributeType) {
		this.roomAttributeType = roomAttributeType;
	}

	@Column (name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column (name = "LANG", nullable = false)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}


