package org.flexpay.bti.persistence;
// Generated 15.11.2007 14:59:52 by Hibernate Tools 3.2.0.b11


import javax.persistence.*;
import java.util.Date;

/**
 * RoomAttribute generated by hbm2java
 */
/*
@Entity
@Table (name = "room_attribute"
		, catalog = "flexpay_db"
)
*/
public class RoomAttribute implements java.io.Serializable {


	private int id;
	private Room room;
	private RoomAttributeType roomAttributeType;
	private Date begin;
	private Date end;
	private String value;

	public RoomAttribute() {
	}


	public RoomAttribute(int id, Date begin, Date end, String value) {
		this.id = id;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	public RoomAttribute(int id, Room room, RoomAttributeType roomAttributeType, Date begin, Date end, String value) {
		this.id = id;
		this.room = room;
		this.roomAttributeType = roomAttributeType;
		this.begin = begin;
		this.end = end;
		this.value = value;
	}

	@Id

	@Column (name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Room_ID")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "Room_Attribute_type_ID")
	public RoomAttributeType getRoomAttributeType() {
		return this.roomAttributeType;
	}

	public void setRoomAttributeType(RoomAttributeType roomAttributeType) {
		this.roomAttributeType = roomAttributeType;
	}

	@Column (name = "begin", nullable = false, length = 0)
	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	@Column (name = "end", nullable = false, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column (name = "value", nullable = false, length = 2000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}


